### ISSUE TITLE
[TWEAK] Consider using an existing format for DDS config files

### ISSUE THREAD

**Issue by tcbrindle** [vector-of-bool/dds#14]
**Existing Behavior and Potential Problems**

DDS's key-value file format is simple and easy to use. 

However, the use of a custom format is not without its downsides. Not only does the extension `.dds` conflict with an existing file type (#2), but even if it did not, editors will by default only recognise `.dds` files as plain text -- if they open them at all. Without built-in support or custom plugins, users will not get the benefit of syntax highlighting and "error squiggles" as they would for other formats.

Furthermore, the use of a custom format means that the authors of tools which wish to interact with DDS will need to write their own parsers and/or generators for `.dds` files.

**Describe Alternatives**

Re-using (a subset of) an existing, well-known, text-based data interchange format for DDS config files would allow editors to open and highlight them correctly and perform simple validation "out of the box", and would allow other tools to re-use existing libraries to read and write compatible files. Potential formats might include TOML, JSON, YAML or (shudder) XML. 

The current format appears to be a near-subset of YAML -- the main difference being that YAML does not allow repeated keys, which are used in DDS (for example) to specify multiple dependencies. This could be avoided by using a sequence instead:

```yaml
# Syntax highlighting for free!
Name: acme-gadgets
Version: 4.3.6
Namespace: acme

Depends:
  - acme-widgets: ^1.4.3
  - acme-gizmos: ~5.6.5
  - acme-utils: ^3.3.0
```

The major downside of YAML is that the specification is fearsomely complicated, with advanced features like anchors and references which are way beyond what DDS requires. A simpler alternative might be TOML, which seems to be a popular choice among recent package managers such as Cargo and Buckeroo. With TOML, the above might be become something like

```toml
[package]
Name = "acme-gadgets"
Version =  "4.3.6"
Namespace = "acme"

[depends]
acme-widgets = "^1.4.3"
acme-gizmos = "~5.6.5"
acme-utils = "^3.3.0"
```

The downside in this case is the need to explicitly wrap strings in quotes. Also worth noting that TOML does not allow the `+` character in keys, so a hypothetical `toolchain.toml` would need look something like:

```toml
Compiler-ID = "Clang"
Cpp-Version = 17        # Not C++-Version
Debug = false
Optimise = true
Cpp-Flags = "-fcoroutines-ts"
Warning-Flags = "-Wall -Wextra"
```
